baseURL = "https://rogchap.com/"
languageCode = "en-au"
title = "Roger Chapman"
theme = "temple"

pygmentsStyle = "friendly"
pygmentsCodeFences = true

enableRobotsTXT=true
enableEmoji=true

disqusShortname = "rogchap"
googleAnalytics = "UA-4155555-8"

[taxonomies]
tag = "tags"

[permalinks]
posts = "/:year/:month/:day/:slug/"
modules = "/:filename/"

[params]
dateformatpretty = "Jan 2, 2006"
description = "Roger is a Software Engineer living in Sydney, Australia. As a polyglot engineer, working with C#, Objective-C (iOS), Java (Android) and Javascript, he has found his passion with the Go programming language."
images = ["tile.png"]
branch = "main"

[author]
email = "rogchap@gmail.com"
github = "rogchap"
twitter = "rogchap"
medium = "rogchap"

[markup.goldmark.renderer]
unsafe = true
